### ISSUE TITLE
It would be nice if max(Number,undefined) returned just the Number

### ISSUE THREAD

**Issue by capre733** [lmccart/p5.js#449]
So we don't have to do things like:

```js
maxMicLevel = max([micLevel, maxMicLevel || 0]);
```

**Comment by lmccart** [comment]
hey all, sorry to be late to this discusssion. I think you've all hit on most of the goals of the library, and this issue opens the question of how far to go in helping beginners / gracefully handling unexpected input. I think the point that @ToonSpin makes about the math becoming kind of fuzzy if we assume undefined means 0 is a good one. I like the idea that some of these functions are really just thin wrappers for things that already exist (eg `Math.max`). it makes a transition to vanilla JS a little easier I think.

I'd suggest that we think more broadly about a system for checking and making console.log messages for unexpected input rather than trying to guess every mistake a user might make. if these messages were of a uniform pattern, we could easily build support into the IDE and give more clear feedback to the user. what do you guys think?

**Comment by ToonSpin** [comment]
> I'd suggest that we think more broadly about a system for checking and making console.log messages for unexpected input rather than trying to guess every mistake a user might make. if these messages were of a uniform pattern, we could easily build support into the IDE and give more clear feedback to the user. what do you guys think?

I like it. Unfortunately I don't know if I personally have the time to help you guys out with that though.

Many compiled / interpreted languages have the concept of different severities, you could make  things like these pop up as warnings in the IDE. Perhaps you should make it easy to write tests to check for that, so that people can easily make a test that asserts that a given action emits such a warning.

**Comment by lmccart** [comment]
@ToonSpin thanks for the thoughts, completely understand your time limitations, no worries!

I'm going to close this issue for now if there are no objections to the alternate direction.
