### ISSUE TITLE
arc positioning breaks when width != height

### ISSUE THREAD

**Issue by ekeneijeoma** [lmccart/p5.js#492]
positioning works when the width and height are the same
ellipse(100,100,100,100);
arc(100,100,100,100,0,TWO_PI);

but not when the height is changed to 200
ellipse(100,100,100,200);
arc(100,100,100,200,0,TWO_PI);

it draw the same ellipse in the same position but the arc drawn ellipse is offset to the left.

**Comment by kevinb7** [comment]
I had a look at the code for ```arc``` and it's doing a couple of things wrong:
- if the arc is stretched in one direction it applies a scale factor by doesn't add a translation to correct for arcs with centers not at (0, 0)
- the scaling also affects the thickness of the curved line such that at one axis the line is thick and at the other it's skinny

![screen shot 2015-01-26 at 11 37 41 pm](https://cloud.githubusercontent.com/assets/1044413/5914532/64a4a386-a5b4-11e4-9db3-521a1e2ef862.png)

Proposed solutions:
- calculate the points of the arc and draw lines between them (this is what processing-js does)
- approximate the arc with a cubic bezier curve, see http://hansmuller-flex.blogspot.ca/2011/04/approximating-circular-arc-with-cubic.html

My preference would be using bezier curves because we'll end up using fewer drawing calls.

**Comment by lmccart** [comment]
sounds good, thanks for looking into this!

**Comment by lmccart** [comment]
closed with https://github.com/lmccart/p5.js/pull/518
